version: "3.8"

services:
  api:
    container_name: ollama
    build:
      context: .
      dockerfile: dockerfile.ollama.cpu
      # dockerfile: dockerfile.ollama.gpu
    ports:
      - "11434:11434"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
